#pragma multi_compile_local __ \
    CAM_COUNT_1 CAM_COUNT_2 CAM_COUNT_3 CAM_COUNT_4 \
    CAM_COUNT_5 CAM_COUNT_6 CAM_COUNT_7 CAM_COUNT_8 \
    CAM_COUNT_9 CAM_COUNT_10 CAM_COUNT_11 CAM_COUNT_12 \
    CAM_COUNT_13 CAM_COUNT_14 CAM_COUNT_15 CAM_COUNT_16

#ifdef CAM_COUNT_1
#define MAXIMUM_COLOR_CAMERA_COUNT 1
#elif CAM_COUNT_2
#define MAXIMUM_COLOR_CAMERA_COUNT 2
#elif CAM_COUNT_3
#define MAXIMUM_COLOR_CAMERA_COUNT 3
#elif CAM_COUNT_4
#define MAXIMUM_COLOR_CAMERA_COUNT 4
#elif CAM_COUNT_5
#define MAXIMUM_COLOR_CAMERA_COUNT 5
#elif CAM_COUNT_6
#define MAXIMUM_COLOR_CAMERA_COUNT 6
#elif CAM_COUNT_7
#define MAXIMUM_COLOR_CAMERA_COUNT 7
#elif CAM_COUNT_8
#define MAXIMUM_COLOR_CAMERA_COUNT 8
#elif CAM_COUNT_9
#define MAXIMUM_COLOR_CAMERA_COUNT 9
#elif CAM_COUNT_10
#define MAXIMUM_COLOR_CAMERA_COUNT 10
#elif CAM_COUNT_11
#define MAXIMUM_COLOR_CAMERA_COUNT 11
#elif CAM_COUNT_12
#define MAXIMUM_COLOR_CAMERA_COUNT 12
#elif CAM_COUNT_13
#define MAXIMUM_COLOR_CAMERA_COUNT 13
#elif CAM_COUNT_14
#define MAXIMUM_COLOR_CAMERA_COUNT 14
#elif CAM_COUNT_15
#define MAXIMUM_COLOR_CAMERA_COUNT 15
#elif CAM_COUNT_16
#define MAXIMUM_COLOR_CAMERA_COUNT 16
#else
#define MAXIMUM_COLOR_CAMERA_COUNT 0
#endif

uniform float4x4 _CameraMatrices[ 16 ];
uniform float4 cameraExtrinsics [ 16 ];
uniform float4 cameraIntrinsics[ 16 * 6 ];
uniform float cameraDepthNearVFX[ 16 ];
uniform float cameraDepthFarVFX[ 16 ];
uniform float4 cameraDepthSize[ 16 ];